### ISSUE TITLE
Choosing the most suitable EGL config

### ISSUE THREAD

**Issue by majorz** [polydraw/polydraw#11]
Right now we are picking the first config from the list provided by eglChooseConfig. We need to iterate over the results and pick the most suitable one.

**Comment by majorz** [comment]
This is now implemented

**Comment by MagaTailor** [comment]
So, if I pull master now, and run with `--features gl` or `--features gles2` it should work?

**Comment by majorz** [comment]
Just to leave a reply here, although we clarified it in the other thread. This is correct and additionally on ARM the default is `gles2` and on non-ARM the default is `gl`.

I will put more detailed information in the documentation as soon as the GLES support is finished and the upcoming new demos I am working on are committed.
